### 1️⃣Caso Datos Válidos y Apto (flujo OK)
POST http://localhost:8099/api/proceso/start
Content-Type: application/json

{
"num_socio": "123456",
"especialidad": "Cardiología",
"motivo": "Chequeo general",
"fecha_turno": "2025-10-26"
}

### 2️⃣Caso Datos Inválidos (Socio vacío)
POST http://localhost:8099/api/proceso/start
Content-Type: application/json

{
  "num_socio": "",
  "especialidad": "Cardiología",
  "motivo": "Chequeo general",
  "fecha_turno": "2025-10-26"
}

### 3️⃣Caso No Apto - Socio con Deuda, mail valido
// Socio con deuda
POST http://localhost:8099/api/proceso/start
Content-Type: application/json

{
  "num_socio": "999", 
  "especialidad": "Cardiología",
  "motivo": "Chequeo general",
  "fecha_turno": "2025-10-26"
}

### 4️⃣Caso No Apto - Especialidad No Cubierta
POST http://localhost:8099/api/proceso/start
Content-Type: application/json

{
  "num_socio": "123456",
  "especialidad": "Oncología",
  "motivo": "Chequeo general",
  "fecha_turno": "2025-10-26"
}

### 5️⃣Caso Datos Inválidos (Motivo vacío)
POST http://localhost:8099/api/proceso/start
Content-Type: application/json

{
  "num_socio": "123456",
  "especialidad": "Cardiología",
  "motivo": "",
  "fecha_turno": "2025-10-26"
}

# NUEVAS PRUEBAS PARA INTEGRADOR

### 6 Lanza timeout (en ValidarDatosPaciente)
POST http://localhost:8099/api/proceso/start
Content-Type: application/json

{
  "num_socio": "123", 
  "especialidad": "Cardiología",
  "motivo": "Chequeo general",
  "fecha_turno": "2025-10-26"
}

### 7 Socio No Registrado - Lanza Error que luego enviara mail exitosamente
 // No registrado, mail valido (NotificarRechazo)
POST http://localhost:8099/api/proceso/start
Content-Type: application/json

{
  "num_socio": "1000",
  "especialidad": "Cardiología",
  "motivo": "Chequeo general",
  "fecha_turno": "2025-10-26"
}

### 8 Socio No Registrado - Lanza Error que intentara enviar mail y lanza error tambien
// No registrado, y mail invalido (NotificarRechazo)
POST http://localhost:8099/api/proceso/start
Content-Type: application/json

{
  "num_socio": "1001", 
  "especialidad": "Cardiología",
  "motivo": "Chequeo general",
  "fecha_turno": "2025-10-26"
}

### 9 No hay disponibilidad de turnos - Lanza Error que luego enviara mail exitosamente
// No registrado, mail valido (NotificarRechazo)
POST http://localhost:8099/api/proceso/start
Content-Type: application/json

{
  "num_socio": "2000", 
  "especialidad": "Cardiología",
  "motivo": "Chequeo general",
  "fecha_turno": "2025-05-20"
}

### 10 No hay disponibilidad de turnos - Lanza Error que intentara enviar mail y lanza error tambien
// No registrado, y mail invalido (NotificarRechazo)
POST http://localhost:8099/api/proceso/start
Content-Type: application/json

{
  "num_socio": "2001", 
  "especialidad": "Cardiología",
  "motivo": "Chequeo general",
  "fecha_turno": "2025-05-20"
}

### 11 Turnos no disponibles
 // Turno no disponible, en RevisarAgenda
POST http://localhost:8099/api/proceso/start
Content-Type: application/json

{
  "num_socio": "2000", 
  "especialidad": "Cardiología",
  "motivo": "Chequeo general",
  "fecha_turno": "2025-05-20"
}

### 12 Notifica turno no disponible, lanza mail invalido
// Turno no disponible, en RevisarAgenda
POST http://localhost:8099/api/proceso/start
Content-Type: application/json

{
  "num_socio": "500", 
  "especialidad": "Cardiología",
  "motivo": "Chequeo general",
  "fecha_turno": "2025-05-20" 
}

### 13 Turno duplicado, lanza error que finaliza proceso
 // Turno duplicado, en ConfirmarTurno
POST http://localhost:8099/api/proceso/start
Content-Type: application/json

{
  "num_socio": "500", 
  "especialidad": "Cardiología",
  "motivo": "Chequeo general",
  "fecha_turno": "2025-10-05"
}

### 14 Fecha invalida, lanza error que finaliza proceso
// Fecha invalida, en ConfirmarTurno
POST http://localhost:8099/api/proceso/start
Content-Type: application/json

{
  "num_socio": "500", 
  "especialidad": "Cardiología",
  "motivo": "Chequeo general",
  "fecha_turno": "20-10-2025" 
}
